eureka/src/main/java/com/example/eureka/EurekaApplication.java
eureka/src/main/resources/application.properties

chore: eureka 설정

---

gateway/src/main/resources/gateway.env

chore: env 파일 제외 설정

---

eureka/src/main/java/com/example/eureka/config/SecurityConfig.java
eureka/src/main/java/com/example/eureka/config/WebConfig.java

chore: eureka 보안 추가

---

gateway/build.gradle
gateway/src/main/java/life/eventory/gateway/GatewayApplication.java
gateway/src/test/java/life/eventory/gateway/GatewayApplicationTests.java

- com.example -> life.eventory

chore: gateway 패키지 경로 변경

---

eureka/build.gradle
eureka/src/main/java/life/eventory/eureka/EurekaApplication.java
eureka/src/main/java/life/eventory/eureka/config/SecurityConfig.java
eureka/src/main/java/life/eventory/eureka/config/WebConfig.java
eureka/src/test/java/life/eventory/eureka/EurekaApplicationTests.java

- com.example -> life.eventory

refactor: eureka 패키지 그룹 변경

---

event/build.gradle
event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/dto/EventDTO.java
event/src/main/java/life/eventory/event/dto/NewEventDTO.java
event/src/main/java/life/eventory/event/entity/Event.java
event/src/main/java/life/eventory/event/repository/EventRepository.java
event/src/main/java/life/eventory/event/service/EventService.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
event/src/main/resources/application.properties

- event 테이블 생성
- 임시 생성, 조회 API 구현
- Related 이슈: #21

feat: event 테이블 및 기초 기능 구현

---

gateway/build.gradle
gateway/src/main/java/life/eventory/gateway/config/GatewayConfig.java
gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java
gateway/src/main/resources/application.properties

- properties 수정 및 라우팅 설정
- SecurityConfig 추가

chore: gateway 및 보안 설정 추가

---

.github/workflows/deploy-gateway.yml

- gateway cicd 워크플로우 프로토타입 작성
- Closed 이슈: #이슈번호 (PR 병합 시 자동으로 이슈 닫힘)
- Related 이슈: #이슈번호 (참고용)

chore: Create deploy-gateway.yml

---

eureka/build.gradle
eureka/src/main/resources/application.properties

refactor: eureka 설정 변경

---

event/src/main/resources/application.properties

- Swagger 경로 변경
- Related 이슈: #21

chore: Event Swagger 경로 변경

---

gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java

chore: gateway get 허용 수정

---

gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java

chore: gateway cors swagger 추가

---

event/src/main/java/life/eventory/event/config/SecurityConfig.java

- 불필요한 cors 제거 (이중 cors 해결)
- Related 이슈: #21

chore: Event CORS 제거

---

event/src/main/java/life/eventory/event/config/SecurityConfig.java
event/src/main/java/life/eventory/event/config/SwaggerConfig.java
gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java

- CORS 허용 및 이중 CORS 방지
- 요청 URL 수정

refactor: Swagger 관련 config 전부 수정

---

activity/src/main/java/life/eventory/activity/entity/ActivityEntity.java

chore: entity 생성

---

activity/src/main/java/life/eventory/activity/entity/ActivityEntity.java

- 작업 1
- Closed 이슈: #이슈번호 (PR 병합 시 자동으로 이슈 닫힘)
- Related 이슈: #이슈번호 (참고용)

fix: 워크플로우 수정 테스트

---

gateway/src/main/resources/application.properties

chore: 활동 서버 요청 라우트 추가

---

gateway/src/main/resources/application.properties

fix: 활동 서버 요청 라우트 번호 수정

---

user/src/main/java/life/eventory/user/controller/UserController.java
user/src/main/java/life/eventory/user/dto/UserDTO.java
user/src/main/java/life/eventory/user/entity/UserEntity.java
user/src/main/java/life/eventory/user/repository/UserRepository.java
user/src/main/java/life/eventory/user/service/UserService.java
user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java

- Controller 생성
- Service 생성
- Repository 생성
- Entity 생서
- DTO 생성
- Related 이슈: #7

chore: user 기본 구조 생성

---

gateway/src/main/resources/application.properties

chore: gateway user 서버 라우트 경로 추가

---

gateway/src/main/resources/application.properties
image/src/main/resources/application.properties

chore: image 용량 제한 100MB 확장

---

image/src/main/java/life/eventory/image/dto/ResponseDTO.java

fix: image 응답 DTO 예시값 변경

---

.github/workflows/deploy-event.yml
.github/workflows/deploy-image.yml
image/src/main/java/life/eventory/image/dto/ReturnDTO.java

- event, image 워크플로우 헬스체크 url 수정
- 누락된 ReturnDTO 추가

fix: event, image 워크플로우 헬스체크 수정

---

image/src/main/java/life/eventory/image/dto/ReturnDTO.java

docs: image 반환 예시값 수정

---

image/src/main/java/life/eventory/image/controller/ImageApi.java
image/src/main/java/life/eventory/image/controller/ImageController.java
image/src/main/java/life/eventory/image/service/ImageService.java
image/src/main/java/life/eventory/image/service/impl/ImageServiceImpl.java

feat: image 삭제 기능 구현

---

image/src/main/java/life/eventory/image/controller/ImageApi.java
image/src/main/java/life/eventory/image/controller/ImageController.java
image/src/main/java/life/eventory/image/service/impl/ImageServiceImpl.java

refactor: image 삭제 로직 수정

---

image/src/main/java/life/eventory/image/controller/ImageApi.java
image/src/main/java/life/eventory/image/controller/ImageController.java

refactor: image 업로드 어노테이션 변경

---

event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/dto/CreateEventRequest.java
event/src/main/java/life/eventory/event/dto/NewEventDTO.java
event/src/main/java/life/eventory/event/service/CommunicationService.java
event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

- 스웨거 타입 오류 수정
- 행사 업로드 실패 시 포스터 이미지 삭제 로직 추가

refactor: 행사 업로드 과정 리팩토링

---

event/src/main/java/life/eventory/event/controller/EventController.java

docs: 행사 업로드 스웨거 요청 타입 명시

---

gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java

chore: gateway 로컬 서버 cors 추가

---

user/build.gradle
user/src/main/java/life/eventory/user/config/AppConfig.java
user/src/main/java/life/eventory/user/config/SecurityConfig.java
user/src/main/java/life/eventory/user/config/SwaggerConfig.java
user/src/main/java/life/eventory/user/controller/UserController.java
user/src/main/java/life/eventory/user/dto/UserLocationRequest.java
user/src/main/java/life/eventory/user/dto/UserSignUpRequest.java
user/src/main/java/life/eventory/user/dto/UserUpdateRequest.java
user/src/main/java/life/eventory/user/entity/UserEntity.java
user/src/main/java/life/eventory/user/service/UserService.java
user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
user/src/main/resources/application.properties

- UserLocationRequest 생성 및 구현
- profile 타입 String -> Long
- swagger 세팅
- mariadb 의존성 추가
- Closes: #11
- Related to: #11

feat: 내 동네 설정

---

event/src/main/java/life/eventory/event/config/SwaggerConfig.java
event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java

docs: 행사 업로드 스웨거 요청 타입 인코드

---

event/src/main/java/life/eventory/event/config/SecurityConfig.java
event/src/main/java/life/eventory/event/controller/EventApi.java
event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

- 행사 등록 이미지 유무 검증 로직 수정
- Controller, Api 분리

refactor: event 이미지 검증 로직 수정 및 스웨거 분리

---

gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java

fix: gateway cors 수정

---

event/src/main/java/life/eventory/event/controller/EventApi.java
event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/dto/UpdateEventRequest.java
event/src/main/java/life/eventory/event/service/EventService.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

feat: event 행사 수정 기능 추가

---

event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

feat: event 행사 수정 기능 수정

---

event/src/main/java/life/eventory/event/config/SecurityConfig.java
image/src/main/java/life/eventory/image/config/SecurityConfig.java

fix: event 시큐리티 cors 수정

---

event/src/main/java/life/eventory/event/EventApplication.java
event/src/main/java/life/eventory/event/dto/EventDTO.java
event/src/main/java/life/eventory/event/dto/NewEventDTO.java
event/src/main/java/life/eventory/event/entity/Event.java
event/src/main/java/life/eventory/event/entity/Tag.java
event/src/main/java/life/eventory/event/repository/EventRepository.java
event/src/main/java/life/eventory/event/repository/TagRepository.java
event/src/main/java/life/eventory/event/service/EventTagService.java
event/src/main/java/life/eventory/event/service/TagNormalizer.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
event/src/main/java/life/eventory/event/service/impl/EventTagServiceImpl.java
event/src/main/resources/application.properties

- 해시태그 기능 추가
- 업로드 시간 추가
- Event.tags 기본값 초기화(@Builder.Default)로 NPE 방지
- 이미지 파일 판별 로직 개선하여 빈 파일 업로드 인식

feat: Event 해시태그 및 이미지 업로드 로직 개선

---

activity/src/main/java/life/eventory/activity/repository/HistoryRepository.java

- findByHistory 구문 파싱 실패 오류 수정 - 쿼리 작성
- Related to: #15

fix: findByHistory 구문 파싱 실패 오류 수정 - 쿼리 작성

---

event/src/main/java/life/eventory/event/config/SwaggerConfig.java
event/src/main/java/life/eventory/event/controller/EventApi.java
event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/repository/EventRepository.java
event/src/main/java/life/eventory/event/service/EventService.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

- 전체 행사 조회 api 구현
- 페이징 기능 구현
- 자동 최신순 정렬
- 이외 정렬 필요 시 프론트와 상의

feat: 전체 행사 조회 기능 추가

---

event/src/main/java/life/eventory/event/controller/EventApi.java
event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/dto/LocationDTO.java
event/src/main/java/life/eventory/event/repository/EventRepository.java
event/src/main/java/life/eventory/event/service/EventService.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

- 행사 거리순 조회 api 구현
- 전체, 거리순 조회에 마감일 필터 기능 구현
- 자동 최신순 정렬

feat: 행사 거리순 조회 기능 추가 및 마감일 로직 추가

---

user/build.gradle
user/src/main/java/life/eventory/user/config/AppConfig.java
user/src/main/java/life/eventory/user/config/SecurityConfig.java
user/src/main/java/life/eventory/user/config/SwaggerConfig.java
user/src/main/java/life/eventory/user/controller/UserController.java
user/src/main/java/life/eventory/user/dto/MultipartFileResource.java
user/src/main/java/life/eventory/user/dto/UserSignUpRequest.java
user/src/main/java/life/eventory/user/entity/UserEntity.java
user/src/main/java/life/eventory/user/service/CommunicationService.java
user/src/main/java/life/eventory/user/service/UserService.java
user/src/main/java/life/eventory/user/service/impl/CommunicationServiceImpl.java
user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java

- CommunicationService, CommunicationServiceImpl 생성 및 구현
- AppConfig, SecurityConfig, SwaggerConfig 수정
- Related to: #8

feat: signup 이미지 업로드 기능 추가

---

gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java

fix: gateway security 설정 변경

---

event/src/main/java/life/eventory/event/controller/EventApi.java

refactor: event 행사 확인 경로 user와 통일

---

event/src/main/java/life/eventory/event/controller/EventApi.java
event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/service/EventService.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

feat: event 행사 단건 조회 기능 추가

---

aggregator/src/main/java/life/eventory/aggregator/config/SwaggerConfigRefreshInterceptor.java
ai/build.gradle
ai/src/main/java/life/eventory/ai/AiApplication.java
ai/src/main/java/life/eventory/ai/controller/AiApi.java
ai/src/main/java/life/eventory/ai/controller/AiController.java
ai/src/main/java/life/eventory/ai/dto/AiEventDTO.java
ai/src/main/java/life/eventory/ai/dto/EventDTO.java
ai/src/main/java/life/eventory/ai/service/AiService.java
ai/src/main/java/life/eventory/ai/service/CommunicationService.java
ai/src/main/java/life/eventory/ai/service/impl/AiServiceImpl.java
ai/src/main/java/life/eventory/ai/service/impl/CommunicationServiceImpl.java
ai/src/main/resources/application.properties

- ai 행사 요약 생성 API 구현
- ai 행사 본문 생성 API 구현

feat: ai 행사 생성, 행사 요약 생성 기능 구현

---

ai/src/main/java/life/eventory/ai/controller/AiApi.java
ai/src/main/java/life/eventory/ai/controller/AiController.java
ai/src/main/java/life/eventory/ai/dto/CreatedEventDTO.java
ai/src/main/java/life/eventory/ai/service/AiService.java
ai/src/main/java/life/eventory/ai/service/impl/AiServiceImpl.java
event/src/main/java/life/eventory/event/controller/EventApi.java
event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/dto/ai/AiEventDTO.java
event/src/main/java/life/eventory/event/dto/ai/CreatedEventInfoDTO.java
event/src/main/java/life/eventory/event/service/CommunicationService.java
event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

- AI 행사 생성 API 구현
- 본문과 그에 맞는 해시태그 자동 생성
- AI 서버와 연동

feat: event 행사 AI 생성 기능 추가

---

event/src/main/java/life/eventory/event/controller/EventApi.java

fix: event 행사 AI 생성 스웨거 문서 수정

---

ai/src/main/java/life/eventory/ai/service/impl/AiServiceImpl.java

fix: 해시태그 생성 # 기호 제외

---

activity/src/main/java/life/eventory/activity/controller/HistoryController.java

- Swagger에서 오류나서 controller에 @ParameterObject 추가
- Related to: #15

fix: 사용자 히스토리 목록 조회 수정

---

event/src/main/java/life/eventory/event/service/ExternalEventInfoAggregator.java

- 타 지역 주소 미스매치 되는 현상 수정
- 대구 컴포넌트 추가

fix: event 주소 검색 대구 컴포넌트 추가

---

user/src/main/java/life/eventory/user/controller/UserAPI.java
user/src/main/java/life/eventory/user/controller/UserController.java
user/src/main/java/life/eventory/user/dto/UserUpdateRequest.java
user/src/main/java/life/eventory/user/service/UserService.java
user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java

- user 정보 수정 시 프로필 이미지 업로드 기능 추가
- Related to: #10

feat : user 정보 업데이트 기능 수정

---

event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/controller/api/EventApi.java
event/src/main/java/life/eventory/event/repository/EventRepository.java
event/src/main/java/life/eventory/event/service/EventService.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

- 주최자 ID로 조회 페이징 처리
- 기타 조회 로직 페이징 파라미터 수정

refactor: event 주최자 ID로 조회 페이징 처리

---

event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/controller/api/EventApi.java
event/src/main/java/life/eventory/event/repository/EventRepository.java
event/src/main/java/life/eventory/event/service/EventService.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

feat: event 주최자 존재 여부 확인 기능 추가

---

event/src/main/java/life/eventory/event/controller/QrController.java
event/src/main/java/life/eventory/event/controller/api/QrApi.java
event/src/main/java/life/eventory/event/dto/EventDTO.java
event/src/main/java/life/eventory/event/entity/Event.java
event/src/main/java/life/eventory/event/repository/EventRepository.java
event/src/main/java/life/eventory/event/service/InMemoryMultipartFile.java
event/src/main/java/life/eventory/event/service/QrService.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
event/src/main/java/life/eventory/event/service/impl/QrServiceImpl.java
event/src/main/resources/application.properties

- QR 발급 기능 구현
- QR 발급 후 image 서버에 저장
- 발급된 image의 id값을 반환
- event에 반환된 qrImage의 ID를 저장
- 행사 ID로 QR 이미지 ID 조회 기능 구현

feat: event QR 발급, 조회 기능 구현

---

user/build.gradle
user/src/main/java/life/eventory/user/config/AuthConfig.java
user/src/main/java/life/eventory/user/controller/JwksController.java
user/src/main/java/life/eventory/user/service/TokenService.java
user/src/main/java/life/eventory/user/service/impl/TokenServiceImpl.java

- RSA 기반 JWT 토큰 발급 기능 구현
- Related to: #24

feat: JWT 토큰 발급

---

user/src/main/java/life/eventory/user/config/AuthConfig.java
user/src/main/java/life/eventory/user/controller/UserController.java
user/src/main/java/life/eventory/user/controller/api/UserAPI.java
user/src/main/java/life/eventory/user/dto/login/LoginRequest.java
user/src/main/java/life/eventory/user/dto/login/LoginResponse.java
user/src/main/java/life/eventory/user/service/TokenService.java
user/src/main/java/life/eventory/user/service/UserService.java
user/src/main/java/life/eventory/user/service/impl/TokenServiceImpl.java
user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
user/src/main/resources/application.properties

- 로그인, 토큰 재발급 API 구현
- Related to: #1

feat: user 로그인, 토큰 재발급 기능 작동 확인

---

activity/src/main/java/life/eventory/activity/config/SwaggerConfig.java
ai/src/main/java/life/eventory/ai/config/SwaggerConfig.java
event/src/main/java/life/eventory/event/config/SwaggerConfig.java
gateway/build.gradle
gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java
gateway/src/main/java/life/eventory/gateway/filter/UserPropagationFilter.java
image/src/main/java/life/eventory/image/config/SwaggerConfig.java
user/src/main/java/life/eventory/user/config/SwaggerConfig.java

- 게이트웨이 토큰 검증 로직 추가
- 타 서버 스웨거에 토큰 헤더 설정 추가
- Related to: #24

feat: 토큰 검증 로직 추가, 타 서버 스웨거 수정

---

user/src/main/java/life/eventory/user/controller/UserController.java
user/src/main/java/life/eventory/user/dto/login/LoginResponse.java
user/src/main/java/life/eventory/user/service/UserService.java
user/src/main/java/life/eventory/user/service/impl/TokenServiceImpl.java
user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java

- id, name, email 반환
- Related to: #24

refactor: user 로그인 반환값 수정

---

gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java

refactor: 행사 생성 임시 개방

---

ai/src/main/java/life/eventory/ai/controller/AiApi.java
ai/src/main/java/life/eventory/ai/controller/AiController.java
ai/src/main/java/life/eventory/ai/dto/activity/HistoryRequest.java
ai/src/main/java/life/eventory/ai/dto/activity/HistoryResponse.java
ai/src/main/java/life/eventory/ai/service/AiService.java
ai/src/main/java/life/eventory/ai/service/CommunicationService.java
ai/src/main/java/life/eventory/ai/service/impl/AiServiceImpl.java
ai/src/main/java/life/eventory/ai/service/impl/CommunicationServiceImpl.java
event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/controller/api/EventApi.java
event/src/main/java/life/eventory/event/dto/activity/HistoryRequest.java
event/src/main/java/life/eventory/event/dto/activity/HistoryResponse.java
event/src/main/java/life/eventory/event/service/CommunicationService.java
event/src/main/java/life/eventory/event/service/EventService.java
event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

- User 해더가 존재할 때 구동
- 활동 서버에 히스토리 내약 저장

refactor: event 행사 조회, AI 요약 생성 시 히스토리 생성

---

activity/src/main/java/life/eventory/activity/controller/HistoryController.java
activity/src/main/java/life/eventory/activity/controller/api/HistoryAPI.java

refactor: 활동 서버 수정

---

gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java

refactor: security 경로 수정

---

event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/controller/api/EventApi.java
event/src/main/java/life/eventory/event/entity/Event.java
event/src/main/java/life/eventory/event/service/EventService.java
event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

feat: event 행사 리스트 해시태그 조회 기능 추가

---

event/src/main/java/life/eventory/event/controller/api/EventApi.java

feat: event 행사 추천 API 엔드포인트 수정

---

activity/src/main/java/life/eventory/activity/controller/ReviewController.java
activity/src/main/java/life/eventory/activity/controller/api/ReviewAPI.java
activity/src/main/java/life/eventory/activity/dto/review/ReviewRequestDTO.java
activity/src/main/java/life/eventory/activity/dto/review/ReviewResponseDTO.java
activity/src/main/java/life/eventory/activity/entity/ReviewEntity.java
activity/src/main/java/life/eventory/activity/repository/ParticipationRepository.java
activity/src/main/java/life/eventory/activity/repository/ReviewRepository.java
activity/src/main/java/life/eventory/activity/service/ReviewService.java
activity/src/main/java/life/eventory/activity/service/impl/ReviewServiceImpl.java

- 참여 행사 리뷰 작성
- 한 행사의 모든 리뷰 조회
- 한 사용자의 평균 평점 조회
- Related to: #19 #20

feature: 참여 행사 리뷰 관련 기능 구현

---

activity/src/main/java/life/eventory/activity/controller/BookmarkController.java
activity/src/main/java/life/eventory/activity/controller/api/BookmarkAPI.java
activity/src/main/java/life/eventory/activity/dto/bookmark/BookmarkResponseDTO.java
activity/src/main/java/life/eventory/activity/entity/BookmarkEntity.java
activity/src/main/java/life/eventory/activity/repository/BookmarkRepository.java
activity/src/main/java/life/eventory/activity/service/BookmarkService.java
activity/src/main/java/life/eventory/activity/service/impl/BookmarkServiceImpl.java

- 행사 북마크 한 횟수 조회 기능 추가
- Related to: #14

feature: 행사 북마크 한 횟수 조회 기능 추가

---

user/src/main/java/life/eventory/user/controller/SubscriptionController.java
user/src/main/java/life/eventory/user/controller/api/SubscriptionAPI.java
user/src/main/java/life/eventory/user/dto/SubscriptionListResponse.java
user/src/main/java/life/eventory/user/entity/SubscriptionEntity.java
user/src/main/java/life/eventory/user/entity/UserEntity.java
user/src/main/java/life/eventory/user/service/CommunicationService.java
user/src/main/java/life/eventory/user/service/SubscriptionService.java
user/src/main/java/life/eventory/user/service/impl/CommunicationServiceImpl.java
user/src/main/java/life/eventory/user/service/impl/SubscriptionServiceImpl.java
user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java

- organizerId 반환 
-> organizerId, organizerName, organizerNickname, profileImageId, profileImageUri 반환
- Related to: #12

feat : 구독 목록 기능 반환값 수정

---

event/src/main/java/life/eventory/event/controller/EventController.java
event/src/main/java/life/eventory/event/controller/api/EventApi.java
event/src/main/java/life/eventory/event/service/EventService.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
user/src/main/java/life/eventory/user/dto/UserUpdateRequest.java
user/src/main/java/life/eventory/user/service/CommunicationService.java
user/src/main/java/life/eventory/user/service/impl/CommunicationServiceImpl.java
user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java

refactor: user 사용자 정보 수정 이미지 삭제 로직 추가

---

activity/src/main/java/life/eventory/activity/controller/BookmarkController.java
activity/src/main/java/life/eventory/activity/controller/api/BookmarkAPI.java
activity/src/main/java/life/eventory/activity/service/BookmarkService.java
activity/src/main/java/life/eventory/activity/service/impl/BookmarkServiceImpl.java
event/src/main/java/life/eventory/event/service/CommunicationService.java
event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java

refactor: 북마크 행사 전체 조회

---

user/src/main/java/life/eventory/user/service/impl/TokenServiceImpl.java

fix: user 뭔가 수정함

---

ai/src/main/java/life/eventory/ai/service/impl/AiServiceImpl.java

refactor: 행사 요약 생성 프롬프트 수정

---

user/src/main/java/life/eventory/user/controller/api/UserAPI.java
user/src/main/java/life/eventory/user/service/impl/EmailServiceImpl.java
user/src/main/resources/application.properties

- UserAPI 사용자 정보 수정 기능 설명 "이메일로 사용자 정보 조회" -> "사용자 정보 조회"
- 행사 등록/수정/정기 알림 메일 내용 수정
- application.properties mail.username/password 환경변수로 수정
- Related to: #7

refactor: 스웨거 문구 수정 및 메일 설정 환경변수로 변경

---

event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java

- 행사 추천 코멘트 요청 HTTP 메소드 수정
- 행사 수정 로직 오류 수정

fix: event 행사 추천 코멘트 HTTP 메소드 수정 및 행사 수정 오류 수정

---

event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java

fix: event 행사 추천 코멘트 쿼리 파라미터 수정

---

event/src/main/java/life/eventory/event/controller/api/EventApi.java
event/src/main/java/life/eventory/event/service/recommender/EventRecommenderImpl.java

refactor: event AI 추천 행사 멘트 수정

---

activity/src/main/java/life/eventory/activity/service/impl/ReviewServiceImpl.java

refactor: API 엔드포인트 오타 수정

---

activity/src/main/java/life/eventory/activity/controller/api/ReviewAPI.java

refactor: 스웨거 수정

---

user/src/main/java/life/eventory/user/dto/UserUpdateRequest.java
user/src/main/java/life/eventory/user/repository/EmailRepository.java
user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java

refactor: 회원가입 이메일 인증 수정

---

user/src/main/java/life/eventory/user/controller/EmailController.java
user/src/main/java/life/eventory/user/service/UserService.java
user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java

- 인증 코드 발송 시 사용자 존재 확인 삭제
- Related to: #9

refactor: 이메일 전송 수정
